variables:
  RUST_CI__PUBLISH_CRATES: hard-xml-derive hard-xml

include:
- remote: 'https://gitlab.com/kevincox/rust-ci/-/raw/v1/gitlab-ci.yml'

test-ui:
  extends: rust-ci:test
  image: rust:1.65.0-slim
  variables:
    RUSTFLAGS: --cfg uitest
